language: php

php:
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - ./bin/phpspec run --config=test/phpspec.yml
  - ./bin/behat --config=test/behat.yml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/build/coverage.xml
