language: node_js
node_js:
  - "8"

branches:
  only:
  - prototype-v0.7.0
  - master

before_install:
  - npm install -g serverless
  - npm install -g @angular/cli
  - sudo apt-get install python3
  - sudo pip install awscli
  - (cd api; openssl aes-256-cbc -K $encrypted_11dfe2bc5063_key -iv $encrypted_11dfe2bc5063_iv -in dashboardhub.pem.enc -out dashboardhub.pem -d)
  - (cd api; openssl aes-256-cbc -K $encrypted_11dfe2bc5063_key -iv $encrypted_11dfe2bc5063_iv -in dashboardhub.test.pem.enc -out dashboardhub.test.pem -d)

install:
  - make install

script:
  - echo 'No tests, this is a PROTOTYPE only'

deploy:
  - provider: script
    script: make install deploy.test
    on:
      branch: prototype-v0.7.0
  - provider: script
    script: make install deploy
    on:
      branch: master
