language: node_js
node_js:
  - "8"

branches:
  only:
  - "prototype-v0.7.0"

before_install:
  - npm install -g serverless
  - npm install -g @angular/cli
  - sudo apt-get install python3
  - sudo pip install awscli

install:
  - make install

script:
  - echo 'No tests, this is a PROTOTYPE only'

after_success:
  - make deploy
