language: php

php:
  - 5.5

before_install:
  - mysql -e "create database IF NOT EXISTS dashboardhub;" -uroot
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo wget -O /usr/local/sbin/install-mozilla-addon http://bernaerts.dyndns.org/download/ubuntu/install-mozilla-addon
  - sudo chmod +x /usr/local/sbin/install-mozilla-addon
  - sudo install-mozilla-addon https://addons.mozilla.org/firefox/downloads/latest/5369/addon-5369-latest.xpi
  - sudo install-mozilla-addon https://addons.mozilla.org/firefox/downloads/latest/1843/addon-1843-latest.xpi
  - wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - php app/console doctrine:schema:update --force
  - php app/console doctrine:fixtures:load --no-interaction
  - php app/console server:start -vvv --env=dev
  - java -jar selenium-server-standalone-2.45.0.jar &

script:
  - ./bin/phpspec run --config=test/phpspec.yml -vvv
  - ./bin/behat --config=test/behat.yml -vvv --suite=dashboardhub_app
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/build/coverage.xml

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - GIT_TAG=build-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - echo $GIT_TAG > VERSION
  - git commit -m "Set build VERSION number $GIT_TAG" VERSION
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GITHUBKEY@github.com/DashboardHub/PipelineDashboard $GIT_TAG > /dev/null 2>&1

deploy:
  provider: heroku
  api_key:
    develop:
      secure: "APuMjriw3g77wca7s6jSL3glCR1dup/ldvxUXyCbVlmbq2P/tRAStrfXYBQvm4GLpEGF8SgeaCUC1WBTo7gUSUWj0fwbkudj/rBxW54wBkNMW86n9tbt07abcxHptUh/IHs3JDHKW23FeXHzNUdFFRogJEHchN6D/DBmWftmpXo="
  app:
    develop: dashboardhub-ci
  run:
    - php app/console doctrine:schema:update --force

env:
  global:
    - secure: "GmEtyPOua9A1W7Wv+Dz1NA/Skh5yiB3VaHk2yaptet5xbAOTo66D4yhlsJFfOI8ZlSUvpEXLzh4B3zKgMzVXUv4lcSnZFP6MLJ6l4pBkivBTWfYRiwMCEZYgS7eAw1WIetFx6fuO//9m0qe33eSyRx0bZQ3b1URqSgf/2xUtX28="
    - secure: "JNtzki5EYmIMnoYOrcnSsFRXXQ+tYrAFoFPOf5DPK2JvXCcmZWEjn1+MpyzvIpQG/jmCJ6iULADhtOeDs2q26X/kXVpcJkx7jlsdGovpJae09PPoarfpYKC+qmTLsA9rrVEB4EOQoWrB1u9qIC2z8/YVujfc7jDSOE6r92Ds758="
    - SYMFONY__DATABASE__HOST="127.0.0.1"
    - SYMFONY__DATABASE__NAME="dashboardhub"
    - SYMFONY__DATABASE__USER="root"
    - SYMFONY__DATABASE__PASSWORD=""

notifications:
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/48b2cf97b6c09c6988ae
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: false     # default: false

branches:
  except:
    - /^build-[0-9a-z\-\/]*/
