language: php

php:
  - 5.5
  - 5.6

matrix:
  allowed_failures:
    - php: 7.0
  fast_finish: true

before_install:
  - openssl aes-256-cbc -K $encrypted_01057e597bbd_key -iv $encrypted_01057e597bbd_iv -in .travis/deploy.pem.enc -out .travis/deploy.pem -d
  - mysql -e "create database IF NOT EXISTS dashboardhub;" -uroot

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --prefer-source
  - php app/console doctrine:schema:update --force
  - php app/console doctrine:fixtures:load --no-interaction
  - php app/console cache:prime

script:
  - ./bin/phpspec run --config=test/phpspec.yml -vvv
  - ./bin/behat --config=test/behat.yml -vvv --suite=dashboardhub_app
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/build/coverage.xml

after_success:
  # tag release
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - GIT_TAG=build-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - echo $GIT_TAG > VERSION
  - git commit -m "Set build VERSION number $GIT_TAG" VERSION
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GITHUBKEY@github.com/DashboardHub/PipelineDashboard $GIT_TAG > /dev/null 2>&1
  # deploy
  - sh .travis/deploy.sh $TRAVIS_BRANCH

env:
  global:
    - secure: "GmEtyPOua9A1W7Wv+Dz1NA/Skh5yiB3VaHk2yaptet5xbAOTo66D4yhlsJFfOI8ZlSUvpEXLzh4B3zKgMzVXUv4lcSnZFP6MLJ6l4pBkivBTWfYRiwMCEZYgS7eAw1WIetFx6fuO//9m0qe33eSyRx0bZQ3b1URqSgf/2xUtX28="
    - secure: "ZIajiUHwiooq5xP9QlPG/GgTrfNbLe9QTMLQd1fc0GMSJRVJhBOT2YqaWRYLPP3jOuCtjOwzFlgER3exaxXU1FBJHXHteCfKuYlidF0JOa4ASadpPkFXdOBZsyFLhoErMxa7TsCGgQmHEpnDqe36448RaWn8ad6HeNvrjTHArDc="
    - secure: "Krew3lipt13cgfQVZ9kI2ZH08QR1KrPHS6XYglmNp90YlrX04cUQ0QBofu4PBpC5X/peKBX1YiGRY9nIfBJgEvLNwzFLEX/qNe2OOarELM/cvzg0/TSS9nl2X7/tBKg7h56Ilmp5jRwlCs+6yAN55AEo41UoPezpNr7GHhqdFOI="
    - secure: "egCIJUSoUQPml4fZDblp0GkIZAtL41nNZhAtUeQ/6DlwvVEEj2zhmNTODpl2fFJtglWjNjFDiClHRTDyvXgguXvYQjZvHJABcnwSmT6JPTR0O5ZTSsBRMXVP3XU25r/zB2MRHcJ57hQqamFhaX+NpIEfJS3l1HXI8Q5w+PCyHQ0="
    - secure: "f1i9VTFeQhMX15v8wf7apjJikn4pfgB4gCnND1Hwcb+QTwXfmxYY7w792e96KQhQHUIo8FxyrX8yEtmsmB8d/RlGEHkXINDXCy2xLwzK2lsLx0/3Bwy68Pf7l1AAWTJ9G0eG5ZbpMfz0LRVGsYKCNvH05OivMLLHZj1HW+7Psk8="
    - SYMFONY__DATABASE__HOST="127.0.0.1"
    - SYMFONY__DATABASE__NAME="dashboardhub"
    - SYMFONY__DATABASE__USER="root"
    - SYMFONY__DATABASE__PASSWORD=""

notifications:
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/48b2cf97b6c09c6988ae
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: true     # default: false

branches:
  except:
    - /^build-[0-9a-z\-\/]*/
