language: node_js
node_js:
  - "8"
branches:
  only:
  - master
  - prototype-v0.8.0
  - /issue-*/
env:
  - NODE_ENV=test

before_install:
  - sudo apt-get install python3
  - sudo pip install awscli
  - npm cache --force clean
  - (cd api; openssl aes-256-cbc -K $encrypted_11dfe2bc5063_key -iv $encrypted_11dfe2bc5063_iv -in secrets.tar.enc -out secrets.tar -d; tar xvf secrets.tar; cp dashboardhub.test.pem dashboardhub.pem)

script:
  - make install.local
  - NODE_ENV=development make api &
  - make test
  - make ui.build

deploy:
  - provider: script
    skip_cleanup: true
    script: make install.test deploy.test
    on:
      branch: prototype-v0.8.0
  - provider: script
    skip_cleanup: true
    script: make install deploy
    on:
      branch: master
