language: php

php:
  - 5.5
  - 5.6

matrix:
  allowed_failures:
    - php: 7.0
  fast_finish: true

before_install:
  - openssl aes-256-cbc -K $encrypted_01057e597bbd_key -iv $encrypted_01057e597bbd_iv -in .travis/deploy.pem.enc -out .travis/deploy.pem -d
  - mysql -e "create database IF NOT EXISTS dashboardhub;" -uroot

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --prefer-source
  - php app/console doctrine:schema:update --force
  - php app/console doctrine:fixtures:load --no-interaction
  - php app/console cache:prime

script:
  - ./bin/phpspec run --config=test/phpspec.yml -vvv
  #- ./bin/behat --config=test/behat.yml -vvv --suite=dashboardhub_app
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/build/coverage.xml

after_success:
  # tag release
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - GIT_TAG=build-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - echo $GIT_TAG > VERSION
  - git commit -m "Set build VERSION number $GIT_TAG" VERSION
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GITHUBKEY@github.com/DashboardHub/PipelineDashboard $GIT_TAG > /dev/null 2>&1
  # deploy
  #- sh .travis/deploy.sh $TRAVIS_BRANCH
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy.pem
  - ssh-add .travis/deploy.pem
  - git remote add ci dokku@prototype.dashboardhub.io:prototype
  - git push prototype $GIT_TAG:master -f

env:
  global:
    - secure: "GmEtyPOua9A1W7Wv+Dz1NA/Skh5yiB3VaHk2yaptet5xbAOTo66D4yhlsJFfOI8ZlSUvpEXLzh4B3zKgMzVXUv4lcSnZFP6MLJ6l4pBkivBTWfYRiwMCEZYgS7eAw1WIetFx6fuO//9m0qe33eSyRx0bZQ3b1URqSgf/2xUtX28="
    - secure: "ZIajiUHwiooq5xP9QlPG/GgTrfNbLe9QTMLQd1fc0GMSJRVJhBOT2YqaWRYLPP3jOuCtjOwzFlgER3exaxXU1FBJHXHteCfKuYlidF0JOa4ASadpPkFXdOBZsyFLhoErMxa7TsCGgQmHEpnDqe36448RaWn8ad6HeNvrjTHArDc="
    - secure: "PRsqVSjkhmfMwhi8LdlD9xg2HxkIkRN9UhrdtIg+8K7VW4/sxD/8QWX+hWP+qEEpZl0OrvEyZhO/rhWN5bD+Z14BgYkqh6kE7iGn7tvqxr5usLl/w8HMecAE+FkKNGcpPI8Dzzd0YrzpwBUMNF4BCkrgek0fXR5KZ3GceJF3U4I="
    - secure: "AVDd5MxOR1sUTAQSXGqjY/28GKhvzcdJDHh4PQ67qjtUGqWG5n04UyQb8i51fd/ndmAQNnA84cT2Sr12ZouWziYgmfzR/1Apwr7p1Mzg/f7OafvnyVQsz6o20Si3+NSMurqcUSQGbb53FqpqnPR9Gbw1VpwhG0CmnALMybPVIQU="
    - secure: "RCpI5pwVkJQkCDMYH87VjI/NAPnSrJdp+N5Ps0ArdcD/0va+SO6V9V4pvnuAZQ18wJHpTfFzRjePEoH+4lkCta7sQ63jWD5bFY2gJf8Aq5/8MMP/4YkrCv8RtjMW38GIJq+qfsNC6FdlN7daIqRnQT0trAc2+ndjkRALoHEW+EY="
    - SYMFONY__DATABASE__HOST="127.0.0.1"
    - SYMFONY__DATABASE__NAME="dashboardhub"
    - SYMFONY__DATABASE__USER="root"
    - SYMFONY__DATABASE__PASSWORD=""

notifications:
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/48b2cf97b6c09c6988ae
      on_success: always  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: true     # default: false

branches:
  except:
    - /^build-[0-9a-z\-\/]*/
