version: --BUILD-VERSION--
server:
  port: 8081
spring:
  resources:
    chain:
      enabled: true
  cache:
    cache-names: foo
    guava:
      spec: maximumSize=500,expireAfterAccess=600s
  datasource:
#      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:test;MODE=MySQL
  jpa:
    hibernate:
      ddl-auto: create-drop
security:
  sessions: ALWAYS
  oauth2:
    client:
      clientId: foo
      clientSecret: bar
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      scope: write:org,repo,user:email,public_repo # https://developer.github.com/v3/oauth/#scopes
    resource:
      userInfoUri: https://api.github.com/user
#      preferTokenInfo: false
logging:
  level:
    org.springframework.security: DEBUG
---
spring:
    profiles: dev
    datasource:
      url: jdbc:mysql://localhost:3306/dashboardhub
      username: ???
      password: ???
    jpa:
      hibernate:
        ddl-auto: create-drop
debug: true
---
spring:
    profiles: test
debug: true
server:
  port: 0
