parameters:
    database_driver: pdo_mysql
    database_host: 192.168.59.103 # 192.168.59.103
    database_port: null
    database_name: dashboardhub
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 8039273f2d3c02497789932f8f6baf4ea2a70b95
    client_id: b8552335dab47905366f
    client_secret: fd319682ebbf3a2ce76350d146891e665c90c365
    github_api:
        base_url: https://api.github.com
    travis_api:
        base_url: https://api.travis-ci.org
    scrutinizer_api:
        base_url: "https://scrutinizer-ci.com"
